version: '3'
services:
  spectre:
    image: ghcr.io/chronicleprotocol/spectre:0.0.0-dev.0
    build:
      context: "../.."
      dockerfile: "./cmd/Dockerfile"
      args:
        APP_NAME: "spectre"
        APP_VERSION: "0.0.0-dev.0"
