version: '3'
services:
  gofer:
    image: ghcr.io/chronicleprotocol/gofer:0.0.0-dev.0
    build:
      context: "../.."
      dockerfile: "./cmd/Dockerfile"
      args:
        APP_NAME: "gofer"
        APP_VERSION: "0.0.0-dev.0"
